src/Entity/Tickets.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TicketsRepository")
 */
class Tickets
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Projects", inversedBy="tickets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $project_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $file;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $file_name;

     /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ticket", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", mappedBy="ticket_id")
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="tickets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $creator;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProjectId(): ?projects
    {
        return $this->project_id;
    }

    public function setProjectId(?projects $project_id): self
    {
        $this->project_id = $project_id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(?string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getFileName(): ?string
    {
        return $this->file_name;
    }

    public function setFileName(?string $file_name): self
    {
        $this->file_name = $file_name;

        return $this;
    }

     /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTicket($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getTicket() === $this) {
                $comment->setTicket(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
            $tag->addTicketId($this);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
            $tag->removeTicketId($this);
        }

        return $this;
    }

    public function getCreator(): ?user
    {
        return $this->creator;
    }

    public function setCreator(?user $creator): self
    {
        $this->creator = $creator;

        return $this;
    }
}

src/Form/TicketsType.php
<?php

namespace App\Form;

use App\Entity\Tickets;
use App\Entity\Tag;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class TicketsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $tags_form = [];
        $tags = $builder->getData()->getTags();
        foreach ($tags as $tag) {
            $tags_form[] = $tag->getName();
        }

        $builder
            ->add('title')
            ->add('type', ChoiceType::class, [
              'choices' => [
                  'bug' => ('bug'),
                  'task' => ('task'),
              ]

            ])
            ->add('status', ChoiceType::class, [
              'choices' => [
                  'new' => ('new'),
                  'in progress' => ('in progress'),
                  'testing' => ('testing'),
                  'done' => ('done'),
              ]
            ])
            ->add('description')
            ->add('tags', TextType::class, ['mapped'=>false, 'data' => implode(', ', $tags_form)])
            ->add('file', FileType::class, [
                'label' => 'Upload file',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypesMessage' => 'Please upload a valid PDF document',
                    ])
                ],
            ])
        ;
    }
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tickets::class,
        ]);
    }
}

src/Controller/TicketsController.php
<?php

namespace App\Controller;

use App\Entity\Tickets;
use App\Entity\Tag;
use App\Entity\Projects;
use App\Entity\Comment;
use App\Entity\User;
use App\Form\TicketsType;
use App\Repository\TicketsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\ProjectsType;
use App\Repository\ProjectsRepository;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\EntityType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @IsGranted("ROLE_USER")
 * @Route("/tickets")
 */
class TicketsController extends AbstractController
{
    /**
     * @Route("/", name="tickets_index", methods={"GET"})
     */
    public function index(TicketsRepository $ticketsRepository): Response
    {
      $creator = $this->getUser()->getId();
      $users = $this->getDoctrine()
            ->getRepository(User::class)
            ->findAll();

        return $this->render('tickets/index.html.twig', [
            'tickets' => $ticketsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="tickets_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $creator = $this->getUser()->getId();
        $projectId = $request->query->get('project_id');
        $ticket = new Tickets();
        $form = $this->createForm(TicketsType::class, $ticket);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $project = $this->getDoctrine()->getRepository(Projects::class)->find($projectId);
            $creator = $entityManager->getRepository(User::class)->find($this->getUser()->getId());

            $ticket->setProjectId($project);
            $ticket->setCreator($creator);


            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($ticket);
            $entityManager->persist($creator);

            $tags_string = $request->request->get('tickets')['tags'];

            $tags = array_map(function ($value) {
                return trim($value);
            }, explode(',', $tags_string));
            foreach ($tags as $tagName) {
                $tag = new Tag();
                $has_tag = $entityManager->getRepository(Tag::class)->findOneBy(
                    ['name' => $tagName]
                );
                if ($has_tag) {
                    $ticket->addTag($has_tag);
                } else {

                    $tag->setName($tagName);
                    $entityManager->persist($tag);
                    $ticket->addTag($tag);

                }
                $entityManager->flush();
            }


            return $this->redirectToRoute('projects_show', ['id' => $projectId]);
        }

        return $this->render('tickets/new.html.twig', [
            'ticket' => $ticket,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tickets_show", methods={"GET", "POST"})
     */
    public function show(Request $request, Tickets $ticket): Response
    {
      $comment = new Comment();
      $creator = $this->getUser()->getId();
      $ticketId = $request->attributes->get('id');

      $commentForm = $this->createFormBuilder($comment)
           ->add('text', TextareaType::class, ['label' => 'New Comment'])
           ->getForm();

       $commentForm->handleRequest($request);

       if ($commentForm->isSubmitted() && $commentForm->isValid()) {
           $comment = $commentForm->getData();
           $entityManager = $this->getDoctrine()->getManager();
           $user = $entityManager->getRepository(User::class)->find($creator);

           $comment->setTicket($ticket);
           $comment->setCreator($user);

           $entityManager->persist($ticket);
           $entityManager->persist($comment);
           $entityManager->persist($user);
           $entityManager->flush();

           echo $ticketId;


           return $this->redirectToRoute('tickets_show', ['id' => $ticketId]);
       }
            return $this->render('tickets/show.html.twig', [
                   'ticket' => $ticket,
                   'comment_form' => $commentForm->createView(),
                   ]);
    }

    /**
     * @Route("/{id}/edit", name="tickets_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Tickets $ticket): Response
    {
        $form = $this->createForm(TicketsType::class, $ticket);
        $form->handleRequest($request);
        $tags_string = $request->request->get('tickets')['tags'];

        $tags = array_map(function ($value) {
            return trim($value);
        }, explode(',', $tags_string));

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            foreach($ticket->getTags() as $tag) {
                $ticket->removeTag($tag);
            }

            foreach ($tags as $tagName) {

                $tag = new Tag();
                $has_tag = $entityManager->getRepository(Tag::class)->findOneBy(
                    ['name' => $tagName]
                );
                if ($has_tag) {
                    $ticket->addTag($has_tag);
                } else {

                    $tag->setName($tagName);
                    $entityManager->persist($tag);
                    $ticket->addTag($tag);
                }
            }
            $this->getDoctrine()->getManager()->flush();

           return $this->redirectToRoute('tickets_index');
        }

        return $this->render('tickets/edit.html.twig', [
            'ticket' => $ticket,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tickets_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Tickets $ticket): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ticket->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($ticket);
            $entityManager->flush();
        }

        return $this->redirectToRoute('tickets_index');
    }

    /**
     * @Route("/{id}/delete_comment", name="comment_delete")
     */
    public function delete_comment(Request $request, $id): Response
    {
        $ticketId = $request->query->get('ticket_id');
        $entityManager = $this->getDoctrine()->getManager();
        $comment = $entityManager->getRepository(Comment::class)->find($id);

        if (!$comment) {
            throw $this->createNotFoundException(
                'No comment found for id '.$id
            );
        }

        $entityManager->remove($comment);
        $entityManager->flush();

        return $this->redirectToRoute('tickets_show', ['id' => $ticketId]);
    }
}

templates/tickets/_delete_form.html.twig
<form method="post" action="{{ path('tickets_delete', {'id': ticket.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ticket.id) }}">
    <button class="btn btn-success">Delete</button>
</form>

templates/tickets/_form.html.twig
        {{ form_start(form) }}
        {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
        {{ form_end(form) }}

templates/tickets/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tickets{% endblock %}

{% block body %}

<div align="center" class="mx-auto" style="width: 300px;">
    <div class="card border-secondary mb-3" style="width: 14rem;">
    </div>
    <div class="card-body text-secondary">
        <h2 class="card-text">Edit Tickets</h2>
    </div>


    {{ include('tickets/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('tickets_index') }}">back to list</a>

    {{ include('tickets/_delete_form.html.twig') }}

{% endblock %}

templates/tickets/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tickets index{% endblock %}

{% block body %}
    <h1>Tickets index</h1>

    <table class="table">
        <thead>
            <tr align="center">
                <th>Id</th>
                <th>Title</th>
                <th>Type</th>
                <th>Status</th>
                <th>Description</th>
                <th>Tags</th>
                <th>File</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ticket in tickets %}
            <tr align="center">
                <td>{{ ticket.id }}</td>
                <td>{{ ticket.title }}</td>
                <td>{{ ticket.type }}</td>
                <td>{{ ticket.status }}</td>
                <td>{{ ticket.description }}</td>
                <td>
                {% for tag in ticket.tags %}
                {{ tag.name }}&ensp;
                {% endfor %}
                </td>
                <td>{{ ticket.file }}</td>
                <td>
                    <a href="{{ path('tickets_show', {'id': ticket.id}) }}">show</a>
                    <a href="{{ path('tickets_edit', {'id': ticket.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('tickets_new') }}">Create new</a>
{% endblock %}

templates/tickets/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tickets{% endblock %}

{% block body %}
    <h1>Create new Tickets</h1>

    {{ include('tickets/_form.html.twig') }}

    <a href="{{ path('tickets_index') }}">back to list</a>
{% endblock %}

templates/tickets/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tickets{% endblock %}

{% block body %}
    <h1>Tickets</h1>

    <table class="table table-dark">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ticket.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ ticket.title }}</td>
            </tr>
            <tr>
                <th>Creator</th>
                <td>{{ ticket.creator.name }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ ticket.type }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ ticket.status }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ ticket.description }}</td>
            </tr>
            <tr>
                <th>Tags</th>
                <td>
                {% for tag in ticket.tags %}
                {{ tag.name }}&ensp;
                {% endfor %}
              </td>
            </tr>
            <tr>
                <th>File_name</th>
                <td>{{ ticket.fileName }}</td>
            </tr>
          </tbody>
    </table>

    <!-- <a href="{{ path('tickets_show', {'id': ticket.id}) }}">back to list</a> -->

    <a class="btn btn-success" href="{{ path('tickets_edit', {'id': ticket.id}) }}">EDIT</a>

    {{ include('tickets/_delete_form.html.twig') }}

    <h1 align="center">
    Comments
    </h1>

    {% for comment in ticket.comments %}

    <div class="my-3">
    <div align="center" class="mx-auto" style="width: 400px;">
    <div align="justify">
        <p>{{ ticket.creator.name }} wrote a comment: {{ comment.text }}</p>
        <p align="right"><a class="btn btn-outline-secondary btn-sm" href="{{ path('comment_delete', {'id': comment.id, 'ticket_id': ticket.id}) }}" role="button">Delete</a></p>
    </div>
    </div>
    </div>
    {% endfor %}
    <div align="center" class="mx-auto" style="width: 400px;">
      <h3>{{ form_start(comment_form) }}
    {{ form_widget(comment_form) }}</h3>
    <div align="right" class="mb-5">
        <button  class="btn btn-success">{{ button_label|default('leave a comment') }}</button>
    </div>
{{ form_end(comment_form) }}
    </div>

{% endblock %}